spring:
  application:
    name: air-to-do
  datasource:
    url: ${db.url}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      username: ${db.username}
      password: ${db.password}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
app:
  vikunja-url: ${vikunja-url}
  vikunja-token: ${vikunja-token}
  telegram-user-id: ${telegram-user-id}

logging:
  level.org.cowary.airtodo: debug
